### ISSUE TITLE
About miss commit at v2 branch

### ISSUE THREAD

**Issue by baboon-king** [vuejs/create-vue-templates#3]
~~Hi! @Jinjiang~~
Hi! @sodatea 

Can you Cherry-Pick this [commit](https://github.com/vuejs/create-vue-templates/commit/869b46aefd7ca6f5525843ec6e1c51ea2a1c2a67) to the "v2" branch?

For https://github.com/vuejs/create-vue/pull/413

I try doing it like this [workflow: manage playground dependency installation separately](https://github.com/vuejs/create-vue/commit/b6cea7702f3d7091678391e952eb29c40207cbac) 

But "v2" is missing this commit.

**Comment by sodatea** [comment]
Done. Thanks!
